### ISSUE TITLE
SEIAR learning rate

### ISSUE THREAD

**Issue by boyeon-kim** [yoon-gu/ezlab-rl#14]

**Comment by boyeon-kim** [comment]
scailing ver. result
<img width="916" alt="image" src="https://github.com/yoon-gu/ezlab-rl/assets/69612871/7736fe3d-f92b-42cd-893b-ceb2419ad599">
<img width="778" alt="image" src="https://github.com/yoon-gu/ezlab-rl/assets/69612871/4394541f-14da-4358-bf67-8464c756385c">

**Comment by yoon-gu** [comment]
이게 아까 말한 learning rate 바꿔서 실험해서 얻은 결과인가요!?

**Comment by boyeon-kim** [comment]
**### initial step**
<img width="531" alt="Pasted Graphic" src="https://github.com/yoon-gu/ezlab-rl/assets/69612871/590fedfd-5d41-453c-a636-9ca1ec59b830">


### **1e-7**
2nd step
<img width="465" alt="step 3" src="https://github.com/yoon-gu/ezlab-rl/assets/69612871/92b8688e-4079-480f-a4fa-ab16d1730984">

7000번 iteration reward
![SLIAR_score_7000](https://github.com/yoon-gu/ezlab-rl/assets/69612871/d1791be9-337f-4d79-9295-d7c8272a0ec1)

**Comment by boyeon-kim** [comment]
### **Learning rate = 1e-5**
<img width="462" alt="Pasted Graphic 4" src="https://github.com/yoon-gu/ezlab-rl/assets/69612871/ebbc1ce6-81d5-4999-9f44-daeda38d2e11">

10000번 iteration reward
![SLIAR_score_10000](https://github.com/yoon-gu/ezlab-rl/assets/69612871/5596ccc2-cbfc-46a9-ad92-294947ddbdf4)

**Comment by boyeon-kim** [comment]
지금 그림 다시 유심히 보니, reward 패널티를 너무 적게 준게 아닌가 하는 생각이 듭니다..
total nu max가 5,000,000을 넘으면 안되는데, 가뿐하게 50,000,000까지 다 사용하려는거 같아서,
reward design 다시 해보겠습니당..!

**Comment by yoon-gu** [comment]
일단 total은 리워드에서 빼고 진행하는걸 추천합니다. 일단 그거 없이 되나 보져
