### ISSUE TITLE
gymnasium 연동 문제 문의

### ISSUE THREAD

**Issue by Rabbit739** [yoon-gu/ezlab-rl#4]
stable-baselines3를 이용한 ppo파일에서 multirun 실행이 되지 않는 것으로 보입니다.

**Comment by Rabbit739** [comment]
우선, sir_ppo의 environment 파일에서 reset 함수의 return에서 {}가 있는 것이 작동이 되지 않아서 일부 수정하여 commit 하였습니다.
이에 따라 reset()을 이용한 다른 결과들도 약간씩 수정했습니다.

이렇게 수정하면, import gym을 한 경우에는
![image](https://github.com/yoon-gu/ezlab-rl/assets/94163977/797f5732-8559-4da0-96e5-54aeed2daf32)
위와 같은 결과가 나오지만,

기존의 코드대로 import gymnasium as gym을 사용한 경우에는 
![image](https://github.com/yoon-gu/ezlab-rl/assets/94163977/63cb3018-e4de-4134-9ff4-279cdb1d9f45)
이렇게 에러가 뜨며 작동하지 않습니다.

gymnasium과 기존 gym의 차이가 궁금합니다..!

**Comment by yoon-gu** [comment]
docker 설치 후 해보세요.
