### ISSUE TITLE
민영의 todos

### ISSUE THREAD

**Issue by yoon-gu** [yoon-gu/ezlab-rl#5]
1. Docker를 설치한다.
2. Docker 예제를 돌려본다. (설치가 잘 되었는지 체크)
3. Dockerfile로 이미지를 만든다. (어색해서 어려울거다)
4. `docker images`로 만든게 있는지 확인한다.
5. `docker run`으로 container를 만든다.
6. `ubuntu`에서 sir ppo를 실행한다.
7. multirun을 테스트해본다.

**Comment by Rabbit739** [comment]
![image](https://github.com/yoon-gu/ezlab-rl/assets/94163977/8de9f865-fdf1-4aad-a541-2a642c007475)

5번까지 한 후, 우선 seiar_ppo.py을 window에서 돌아가게 수정해 뒀어서 seiar_ppo.py를 돌려봤습니다. (sir_ppo.py는 일부 함수에 대해 return 수정을 하지 않았습니다.)

![image](https://github.com/yoon-gu/ezlab-rl/assets/94163977/bc6a05bd-f34e-47fb-9b8d-5ab90f30f2bb)

n_steps에 대해 multirun을 돌려보았는데, 여전히 첫번째 작업이 끝난 후에 다음 작업을 합니다 (동시에 진행되지 않습니다)
multirun 파일이 생기는 것은 확인했습니다!

파일은 4-hydra-multirun-체크 브랜치에 있는 파일을 돌렸습니다!

**Comment by yoon-gu** [comment]
https://hydra.cc/docs/plugins/joblib_launcher/

이거대로 해보세요

**Comment by Rabbit739** [comment]
멀티런 돌아가는 것 확인했습니다!
